### ISSUE TITLE
Extract editable files outside of code base

### ISSUE THREAD

**Issue by boutchitos** [RobotTraders/EnvelopeMulti#4]
When dealing with a source control system like git (or with code at all), you don't want the user having to modify the code base to edit its settings.

Best approach is to have all editable files be outside of the code. At the root of the repository is acceptable. Outside is best.

What should not go under `code` folder:
* parameters
* run_{SYMBOL}.py copies (from older bot)
* run_envelope_{TIMEFRAME}.sh copies (from older bot)
* log files
* tracking files

I know you want it to be simple for the user having all in one place, but this complicate operations anyway:
* Updating the code base after a change (git pull), with a probability of having a conflict (they can't solve that)
* More path navigation in shell to go to the file to edit (cd a/b/c then nano then cd ../../..)
* More path adjustment in bash file
* Questioning _where is my log?_, _where is my bash script?_

Parameters could be provided through a config file: `run_envelope.py --settings settings.json`  (or yaml file)
For the others, I think it is just a matter of moving them and adjusting accordingly. They don't affect the user that much, it is even better with the new async bot.

**Comment by RobotTraders** [comment]
I want to stick to having a "run.py" where all parameters and account configurations are set by the user. This keeps things simple and allows for easy expansion later—so that in the future, multiple strategies could be managed from this master file. I had thought about a seperate .json, but I am afraid it could be too restrictive given these prospects and not having decided how to handle them.

Regarding naming conventions, I agree that "code" is typically reserved for something the user never touches. I’d rather stick to the approach I have started to avoid unnecessary changes that could break previous videos explanations. For a better separation though, I think a good idea is to keep putting core logic/code into the "utilities" folder (with meaningfull subfolders etc) while keeping everything else open for users to modify—whether it’s for running strategies, analysis, or anything else.

**Comment by boutchitos** [comment]
> I want to stick to having a "run.py" where all parameters and account configurations are set by the user. This keeps things simple and allows for easy expansion later—so that in the future, multiple strategies could be managed from this master file. I had thought about a seperate .json, but I am afraid it could be too restrictive given these prospects and not having decided how to handle them.

Yep, this is something to think of. With the actual async bot, you can't trade with many sub accounts (suppose you want different settings for a coin, as a test, or as a strategy). Having params outside of the code could let you run the code twice. Or, with you preferred way of keeping params with the code, you could handle sub accounts into the PARAMS. But, the more you will want to _do this, and do that_, the more it will complexity the code.

I'm on the side of having parameters outside, so I'll give a YAML exemple:

```
accounts:
  my-sub-account-1:
    exchange: bitget
    api-key: "..."
    passphrase: "..."
    secret: "..."

  my-sub-account-2:
    exchange: bitget
    api-key: "..."
    passphrase: "..."
    secret: "..."

trading-bots:
  - envelope:
    account: my-sub-account-1
    leverage: 1
    timeframe: 15m
    low_bands: [0.05, 0.07, 0.09]
    high_bands: [0.05, 0.07, 0.09]
    coins:
      - BTC
      - ETH

  - envelope:
    account: my-sub-account-2
    leverage: 2
    timeframe: 1h
    low_bands: [...]
    high_bands: [...]
    coins:
      - BTC
      - ETH

  - trend:
    ... # trend bot settings here...
```
